# config file for juputer-fan-control.service

loop_interval: 0.5
base_hwmon_path: "/sys/class/hwmon/"

fan_hwmon_name: jupiter
fan_min_speed: 10
fan_threshold_speed: 1500
fan_max_speed: 7300
fan_gain: 10

devices:
  - hwmon_name: acpitz
    nice_name: CPU
    max_temp: 90
    temp_deadzone: 2
    file: temp1_input
    type: quadratic
    A: 2.174
    B: -171.74
    C: 4926
    T_threshold: 45
    # quadratic fit {{45,1600},{80,5100},{91,7300}} 

  - hwmon_name: amdgpu
    nice_name: GPU
    max_temp: 90
    temp_deadzone: 2
    file: temp1_input
    type: quadratic
    A: 2.174
    B: -171.74
    C: 4926
    T_threshold: 45
    # quadratic fit {{45,1600},{80,5100},{91,7300}} 

  - hwmon_name: nvme
    nice_name: SSD
    max_temp: 70.0
    temp_deadzone: 3
    file: temp1_input
    type: pid
    bandwidth: 25
    Kp: 4000
    Ki: 20
    Kd: 0
    windup: 50

  - hwmon_name: jupiter
    nice_name: CHG
    max_temp: 10000
    temp_deadzone: 0
    file: curr1_input
    type: quadratic
    A: 0
    B: 0
    C: 2000
    T_threshold: 1
