# config file for juputer-fan-control.service


fast_loop_interval: 0.2
slow_loop_interval: 1   # TODO test this out
control_loop_ratio: 5
base_hwmon_path: /sys/class/hwmon/
charge_state_path: /sys/class/power_supply/BAT1/status

fan_hwmon_name: steamdeck_hwmon
fan_hwmon_name_alt: jupiter
fan_min_speed: 10
fan_threshold_speed: 2000
fan_max_speed: 7300
#TODO: integrate new variables into fancontrol.py
fan_min_time_on: 120
fan_gain: 10
ec_ramp_rate: 10



sensors:
  - hwmon_name: amdgpu
    nice_name: P_APU
    sensor_name: power1_average
    
    # TODO make sure logic for n ->t works
    sensor_time_avg: 24
    low_power_threshold: 7 #TODO check this works

devices:
  - hwmon_name: acpitz
    nice_name: CPU
    max_temp: 90
    temp_deadzone: 0 # TODO remove hysteresis, change to deadzone
    sensor_name: temp1
    poll_mult: 1
    type: ffquad
    T_threshold: 45
    A_quad: .762
    B_quad: -26.7
    C_quad: 1257
    A_ff: 250
    B_ff: -1750
    # quadratic fit (60,2400)(80,4000)(95,5600)
    # linear fit (7,0),(15,2000)
  
  - hwmon_name: amdgpu
    nice_name: GPU
    max_temp: 90
    temp_deadzone: 0
    sensor_name: temp1
    poll_mult: 1
    type: ffquad
    T_threshold: 45
    A_quad: .762
    B_quad: -26.7
    C_quad: 1257
    A_ff: 250
    B_ff: -1750
    # quadratic fit (60,2400)(80,4000)(95,5600)
    # linear fit (7,0),(15,2000)


  # - hwmon_name: amdgpu
  #   nice_name: GPU
  #   poll_mult: 1
  #   max_temp: 90
  #   temp_deadzone: 2
  #   sensor_name: temp1
  #   type: quadratic
  #   A: 2.286
  #   B: -188.6
  #   C: 5457
  #   T_threshold: 55
  #   # quadratic fit {{55, 2000}, {80, 5000}, {90, 7000}}

  # - hwmon_name: nvme
  #   nice_name: SSD
  #   poll_mult: 20
  #   max_temp: 90.0
  #   temp_deadzone: 3
  #   sensor_name: temp1
  #   type: quadratic
  #   A: 3.06
  #   B: -286.7
  #   C: 6510
  #   T_threshold: 55
  #   # quadratic fit {{55, 0}, {83, 3800}, {90, 5500}}