# config file for juputer-fan-control.service
#TODO in testing, remove this line when ready for release

fast_loop_interval: 0.2
slow_loop_interval: 1   # TODO test this out
control_loop_ratio: 5
base_hwmon_path: /sys/class/hwmon/
charge_state_path: /sys/class/power_supply/BAT1/status

fan_hwmon_name: steamdeck_hwmon
fan_hwmon_name_alt: jupiter
fan_min_speed: 10
fan_threshold_speed: 1500
fan_max_speed: 7300
fan_min_time_on: 120
fan_gain: 10
ec_ramp_rate: 10

sensors:
  - hwmon_name: amdgpu
    nice_name: P_APU
    sensor_name: power1_average
    sensor_time_avg: 24
    low_power_threshold: 7

devices:
  - hwmon_name: acpitz
    nice_name: CPU
    max_temp: 90
    temp_hysteresis: 5
    sensor_name: temp1
    poll_mult: 1
    type: quadratic
    A: 2.286
    B: -188.6
    C: 5457
    T_threshold: 55
    # quadratic fit {{55, 2000}, {80, 5000}, {90, 7000}}

  - hwmon_name: amdgpu
    nice_name: GPU
    poll_mult: 1
    max_temp: 90
    temp_hysteresis: 5
    sensor_name: temp1
    type: quadratic
    A: 2.286
    B: -188.6
    C: 5457
    T_threshold: 55
    # quadratic fit {{55, 2000}, {80, 5000}, {90, 7000}}

  - hwmon_name: nvme
    nice_name: SSD
    poll_mult: 30
    max_temp: 90.0
    temp_deadzone: 3
    sensor_name: temp1
    type: quadratic
    A: 4.57
    B: -531
    C: 17394
    T_threshold: 55
    # quadratic fit {{60, 2000}, {78, 3800}, {85, 5300}}