# config file for juputer-fan-control.service

loop_interval: 0.2
control_loop_ratio: 5
base_hwmon_path: /sys/class/hwmon/
charge_state_path: /sys/class/power_supply/BAT1/status

fan_hwmon_name: steamdeck_hwmon
fan_hwmon_name_alt: jupiter
fan_min_speed: 10
fan_threshold_speed: 1500
fan_max_speed: 7300
fan_gain: 10
ec_ramp_rate: 10

sensors:
  - hwmon_name: amdgpu
    nice_name: P_APU
    sensor_name: power1_average
    n_sample_avg: 120

devices:
  - hwmon_name: acpitz
    nice_name: CPU
    max_temp: 90
    temp_deadzone: 2
    sensor_name: temp1
    poll_mult: 1
    type: quadratic
    A: 2.286
    B: -188.6
    C: 5457
    T_threshold: 55
    # quadratic fit {{55, 2000}, {80, 5000}, {90, 7000}}

  - hwmon_name: amdgpu
    nice_name: GPU
    poll_mult: 1
    max_temp: 90
    temp_deadzone: 2
    sensor_name: temp1
    type: quadratic
    A: 2.286
    B: -188.6
    C: 5457
    T_threshold: 55
    # quadratic fit {{55, 2000}, {80, 5000}, {90, 7000}}

  - hwmon_name: nvme
    nice_name: SSD
    poll_mult: 20
    max_temp: 90.0
    temp_deadzone: 3
    sensor_name: temp1
    type: quadratic
    A: 3.06
    B: -286.7
    C: 6510
    T_threshold: 55
    # quadratic fit {{55, 0}, {83, 3800}, {90, 5500}}